# Generated by Django 2.0.2 on 2019-12-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191226_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imageRathan',
            new_name='image',
        ),
    ]
